"""
Software development domain agents.

Agents specialized in code generation, testing, and architectural review.
"""

from typing import Optional
from .base import SyncBaseAgent


class CodeGenerationAgent(SyncBaseAgent):
    """
    Generates code based on requirements and specifications.
    """
    
    def __init__(self):
        super().__init__(
            name="code_generation",
            description="Generates code based on requirements and context",
        )
    
    def invoke(
        self,
        user_input: str,
        context: Optional[list[str]] = None,
    ) -> str:
        context_str = ""
        if context:
            context_str = f"\n\nContext:\n" + "\n".join(context)
        
        # Mock LLM invocation - in production, call actual model
        response = f"""# Code Generation Agent Response

## Request
{user_input}

## Generated Implementation
```python
# Mock implementation based on request
def solution(input_data):
    '''Generated function to solve: {user_input[:50]}...'''
    # In production, real Qwen model would generate actual code here
    result = process_input(input_data)
    return result

def process_input(data):
    '''Helper function'''
    # Implementation details generated by model
    return data
```

## Notes
- Follows architectural patterns from retrieved context
- Suitable for integration into existing codebase{context_str}
"""
        return response


class UnitTestingAgent(SyncBaseAgent):    
    def __init__(self):
        super().__init__(
            name="unit_testing",
            description="Generates comprehensive unit tests for code",
        )
    
    def invoke(
        self,
        user_input: str,
        context: Optional[list[str]] = None,
    ) -> str:
        context_str = ""
        if context:
            context_str = f"\n\nContext from codebase:\n" + "\n".join(context[:2])
        
        response = f"""# Unit Testing Agent Response

## Test Target
{user_input}

## Generated Test Suite
```python
import pytest
from unittest.mock import Mock, patch

class TestGeneratedCode:
    '''Test suite generated for: {user_input[:40]}...'''
    
    def test_normal_case(self):
        '''Test normal operation with valid inputs'''
        # Test implementation generated by model
        assert True
    
    def test_edge_case_empty_input(self):
        '''Test with empty/null inputs'''
        assert True
    
    def test_error_handling(self):
        '''Test error conditions and recovery'''
        assert True
    
    def test_boundary_conditions(self):
        '''Test boundary values'''
        assert True
```

## Coverage Report
- Line Coverage: ~95%
- Branch Coverage: ~88%
- Edge Cases: 4 identified and tested{context_str}
"""
        return response


class ArchitecturalReviewAgent(SyncBaseAgent):
    def __init__(self):
        super().__init__(
            name="architectural_review",
            description="Reviews code and designs for architectural fitness",
        )
    
    def invoke(
        self,
        user_input: str,
        context: Optional[list[str]] = None,
    ) -> str:
        context_str = ""
        if context:
            context_str = f"\n\nArchitectural Guidelines Applied:\n" + "\n".join(context[:2])
        
        response = f"""# Architectural Review Agent Response

## Code/Design Under Review
{user_input}

## Architectural Assessment

### Strengths
✓ Follows separation of concerns principle
✓ Clear interface contracts defined
✓ Good modularity and reusability
✓ Appropriate use of design patterns

### Areas for Improvement
• Consider dependency injection for better testability
• Add comprehensive error handling strategy
• Document public API contracts more explicitly

### Recommendations
1. **Refactor for Single Responsibility**: Break down complex functions
2. **Add Abstraction Layer**: Introduce interfaces for external dependencies
3. **Improve Error Handling**: Define clear exception hierarchy
4. **Document Design Decisions**: Add architecture decision records (ADRs)

### Pattern Alignment
- Domain-Driven Design: Partially Applied
- SOLID Principles: 4/5 satisfied
- Clean Architecture: Well-aligned
- Microservice Readiness: Medium (with proposed changes)

## Severity Assessment
- Critical Issues: 0
- Important Issues: 2
- Minor Issues: 3
- Recommendations: 4{context_str}
"""
        return response